<?php
namespace Ryzom\Sheets;

use Ryzom\Common\EVisualSlot;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-08 at 19:14:21.
 */
class VisualSlotTabTest extends \PHPUnit\Framework\TestCase {
	/**
	 * @covers Rrs\Ryzom\VisualSlotTab
	 */
	public function testLoad() {
		$buffer = file_get_contents(__DIR__.'/_files/visual_slot.tab');
		$vs = new VisualSlotManager();
		$vs->load($buffer);

		$this->assertFalse($vs->findByIndex(0, EVisualSlot::ARMS_SLOT));
		$this->assertFalse($vs->findBySheetId(0, EVisualSlot::ARMS_SLOT));

		$sheetid = $vs->findByIndex(1, EVisualSlot::ARMS_SLOT);
		$this->assertEquals(5604910, $sheetid);

		$index = $vs->findBySheetId(5604910, EVisualSlot::ARMS_SLOT);
		$this->assertEquals(1, $index);
	}

	/**
	 * @covers Rrs\Ryzom\VisualSlotTab
	 */
	public function testSerialize() {
		$buffer = file_get_contents(__DIR__.'/_files/visual_slot.tab');
		$vs = new VisualSlotManager();
		$vs->load($buffer);
		$expected = serialize($vs);

		// create class and serialize it again.
		// we should get same string back
		$vsNew = unserialize($expected);
		$serialized = serialize($vsNew);

		$this->assertEquals($expected, $serialized);
	}

}
